### ISSUE TITLE
خطا در هنگام استفاده کردن محصول مصرفی

### ISSUE THREAD

**Issue by davidramezani** [cafebazaar/Poolakey#76]
در هنگام فراخوانی متد consumeProduct بعضی مواقع با خطای زیر مواجح میشویم و هیچ یک از کال بک های consumeSucceed و consumeFailed فراخوانی نمی شود.
جزییات خطا :

`Handler (android.os.Handler) {1c93f6c} sending message to a Handler on a dead thread
java.lang.IllegalStateException: Handler (android.os.Handler) {1c93f6c} sending message to a Handler on a dead thread
	at android.os.MessageQueue.enqueueMessage(MessageQueue.java:569)
	at android.os.Handler.enqueueMessage(Handler.java:778)
	at android.os.Handler.sendMessageAtTime(Handler.java:727)
	at android.os.Handler.sendMessageDelayed(Handler.java:697)
	at android.os.Handler.post(Handler.java:427)
	at ir.cafebazaar.poolakey.thread.BackgroundThread.execute(BackgroundThread.kt:15)
	at ir.cafebazaar.poolakey.thread.BackgroundThread.execute(BackgroundThread.kt:6)
	at ir.cafebazaar.poolakey.billing.connection.ServiceBillingConnection.consume(ServiceBillingConnection.kt:309)
	at ir.cafebazaar.poolakey.BillingConnection$consume$1.invoke(BillingConnection.kt:100)
	at ir.cafebazaar.poolakey.BillingConnection$consume$1.invoke(BillingConnection.kt:25)
	at ir.cafebazaar.poolakey.BillingConnection.runOnCommunicator(BillingConnection.kt:163)
	at ir.cafebazaar.poolakey.BillingConnection.consume(BillingConnection.kt:99)
	at ir.cafebazaar.poolakey.Payment.consumeProduct(Payment.kt:106)`

**Comment by farhadrazzaghi** [comment]
This bug has been fixed in recent updates of Cafe Bazaar client.

**Comment by DHosseiny** [comment]
Close as farhad sayed it is fixed
